spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/examenTest
        username: postgres
        password: 1234
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
server:
    port: 8080
    error:
        include-message: always
security:
    secret:
        key: java16
logging:
    level:
        org.springframework.security: DEBUG
        org.springframework.web: DEBUG


